-- ═══════════════════════════════════════════════════════════════════════════
--  Bitácora de movimientos de cotización (2026-09-29)
--  Migración aplicada: `bitacora_de_cotizaciones`
--
--  Elias: "Ayer me mencionaron que yo me meto a hacer cambios y no les aviso a
--  los directores, y que eso los destantea. Sería interesante un botón que
--  pueda yo enviarles el resumen de sesión de movimientos consolidado. No
--  quiero paso por paso porque sería mucho, sino algo procesado. Y que solo se
--  mande si pico el botón."
--
--  ── Por qué TRIGGERS y no instrumentar los editores ─────────────────────
--
--  Una cotización se edita desde CINCO editores (ESP, Ilum, Cortinas,
--  Proyecto, Distribución), desde Cotizaciones.tsx, desde ImportCotizaciones,
--  desde CotizarConIA y desde el MCP del bot. Instrumentar cada punto de
--  escritura serían decenas de llamadas, y la que se olvide no avisa NADA —
--  sin forma de notarlo, porque un log que no registra se ve igual que un día
--  sin cambios. El trigger no se puede olvidar: escriba quien escriba, por la
--  UI o por SQL, queda.
--
--  `activity_log` ya existía con la forma exacta que hacía falta
--  (entity_type, entity_id, action, actor_id, old_value, new_value, metadata)
--  y con CERO filas: otra tabla construida y nunca conectada, como
--  `notifications`. Se usa esa en vez de crear una nueva.
--
--  ── Decisiones ──────────────────────────────────────────────────────────
--
--  · entity_id es SIEMPRE la cotización, aunque el cambio sea de un renglón o
--    de un área. El id del renglón vive en metadata. Si cada uno guardara su
--    propio id, armar el resumen exigiría tres consultas encadenadas y las
--    áreas ya borradas quedarían huérfanas.
--  · NO se registra quotations.total ni updated_at: los mueve otro trigger en
--    cada cambio de renglón, así que registrarlos duplicaría cada evento. El
--    total se calcula al armar el resumen contra el del último aviso.
--  · activity_log NO tiene política de INSERT. Lo llenan los triggers, que son
--    SECURITY DEFINER. Así la bitácora no se puede manipular desde la app.
--
--  ── Qué se captura ──────────────────────────────────────────────────────
--
--  quotation_items  → item_agregado · item_quitado · item_cantidad ·
--                     item_precio · item_sustituido
--  quotation_areas  → area_agregada · area_quitada · area_renombrada
--  quotations       → etapa · dueno · renombrada, y del JSON de `notes`:
--                     sistema_agregado · sistema_quitado ·
--                     sistema_apagado · sistema_prendido ·
--                     ajuste_descuento · ajuste_tipoCambio · ajuste_currency ·
--                     ajuste_ivaRate · ajuste_programacion · ajuste_nominaPct
--
--  `systems_no_suma` es lo que en el cotizador se ve como "apagar un sistema",
--  y no es cosmético: significa que ese sistema no se vendió y Compras deja de
--  comprarle (ver src/lib/sistemasVendidos.ts). Por eso tiene evento propio.
--
--  ── Tabla nueva: quotation_avisos ───────────────────────────────────────
--
--  Cada envío deja aquí su renglón: cuándo, quién, a quiénes, el texto que se
--  mandó y el total de ese momento. Es la frontera de "desde el último aviso"
--  —cada movimiento se reporta exactamente una vez, ni se repite ni se
--  escapa— y de paso es el acuse de qué se le dijo a quién.
--
--  ── Verificación ────────────────────────────────────────────────────────
--
--  Contra una cotización real, dentro de una transacción revertida: se agregó
--  un renglón, se le cambió la cantidad, se agregó un área, se apagó CCTV, se
--  movió el descuento y se borró el renglón. Los 6 eventos quedaron con su
--  área y su detalle. El rollback dejó activity_log en 0 filas.
--
--  Ver el cuerpo completo en la migración `bitacora_de_cotizaciones`.
--  La consolidación a lenguaje humano vive en src/lib/bitacoraCotizacion.ts.
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
--  ⚠️ CORRECCIÓN EL MISMO DÍA — la bitácora rompió producción (2026-09-29)
--  Migración: `bitacora_cot_actor_correcto_y_no_fatal`
--
--  Elias: "Está marcando error cuando creas un área."
--
--    Error al crear área: insert or update on table "activity_log" violates
--    foreign key constraint "activity_log_actor_id_fkey"
--
--  ── La causa ────────────────────────────────────────────────────────────
--
--  `bitacora_cot` insertaba `actor_id = auth.uid()`. Pero:
--
--      activity_log_actor_id_fkey  FOREIGN KEY (actor_id) → app_users(id)
--
--  y en este ERP **`auth.uid()` NO es `app_users.id`**. El puente es
--  `app_users.auth_user_id`; son dos columnas distintas de la misma tabla y
--  no coinciden en ninguna de las 20 filas. Con un usuario real la inserción
--  se rechazaba, y como el registro cuelga de un TRIGGER, el rechazo abortaba
--  la transacción COMPLETA del usuario: no se podía crear un área, ni agregar
--  un renglón, ni editar la cotización. Todas las escrituras registradas.
--
--  Los helpers de RLS que escribí el mismo día (`usuario_real`, `es_area`,
--  `mi_area`, `soy_bot`) SÍ usan `auth_user_id`. El error fue solo aquí.
--
--  ── Por qué la verificación no lo vio ───────────────────────────────────
--
--  La corrí por el MCP de Supabase, o sea con la service key: ahí `auth.uid()`
--  es NULL, y NULL satisface cualquier FK. Las 56 filas que dejó la carga del
--  VIMAR tienen actor_id NULL por eso mismo. El navegador manda un uid real y
--  se rechaza.
--
--    **Una prueba corrida con la identidad equivocada no es una prueba.**
--    Un trigger que depende de quién escribe se verifica simulando la sesión:
--      begin;
--        set local role authenticated;
--        select set_config('request.jwt.claims',
--          json_build_object('sub','<auth uid real>','role','authenticated')::text, true);
--        ...la escritura de verdad...
--      rollback;
--    Eso además ejercita las políticas de RLS, que la service key se salta.
--
--  ── El arreglo, en dos partes ───────────────────────────────────────────
--
--  1. `public.mi_app_user()` (NUEVA) — `app_users.id` del usuario en sesión,
--     buscado por `auth_user_id`. NULL para la service key, los bots y un
--     instalador sin fila en app_users; NULL es válido en la FK, así que esos
--     casos quedan registrados sin nombre en vez de reventar. **Cualquier
--     columna que apunte a app_users(id) tiene que pasar por aquí.**
--     De paso es la identidad que el resumen necesita para decir quién movió
--     qué: `auth.uid()` no se puede unir con nada que muestre un nombre.
--
--  2. El insert va dentro de `begin ... exception when others then raise
--     warning`. **La bitácora ya no puede tumbar la operación que observa.**
--     Si falla se pierde el registro, no el trabajo, y queda el warning en el
--     log de Postgres para investigar el hueco.
--
--     Esto vale para cualquier trigger de auditoría futuro: el observador no
--     puede ser un punto de falla de lo observado. La captura por trigger es
--     lo correcto (no se puede olvidar), pero entonces su costo es que hereda
--     la transacción del usuario, y eso se paga con el manejador.
--
--  ── Verificación (esta vez con la identidad correcta) ───────────────────
--
--  Simulando la sesión de Alfredo Rosas (Ventas_Ingenieria, no DG), todo
--  dentro de begin/rollback:
--
--  | prueba                                    | resultado                    |
--  |-------------------------------------------|------------------------------|
--  | crear área                                | creada · 1 evento · actor OK |
--  | agregar renglón / cambiar cantidad / borrar| 3 eventos · actor OK        |
--  | reproducción del código viejo             | 23503, el error de Elias     |
--  | log roto a propósito (CHECK que falla)    | **área creada · 0 eventos**  |
--
--  El cuarto es el que importa: con la bitácora inservible, la operación del
--  usuario pasa igual. Se probó agregando un `check (action <> 'area_agregada')`
--  dentro de la transacción revertida.
--
--  Después: activity_log en 56 filas (las de antes), 0 filas de prueba, 0
--  constraints sobrevivientes.
--
--  ── Barrido de la misma clase de error ──────────────────────────────────
--
--  4 tablas apuntan a app_users(id): activity_log.actor_id (era la rota),
--  action_items.owner_user_id, notifications.user_id, sla_config.created_by.
--  Las otras tres se llenan desde la app con `authUser.id`, que sale de
--  `app_users.id` en AuthContext — correctas. Ninguna otra función de la base
--  inserta `auth.uid()` en una columna así.
-- ═══════════════════════════════════════════════════════════════════════════
