-- ═══════════════════════════════════════════════════════════════════════════
--  PERMISOS DE VERDAD EN LA BASE — 2026-09-27
--
--  Copia de repo de las migraciones aplicadas. Elias noto que
--  grok_ui_crm@omniious.com "parecia tener acceso a todo". Lo tenia, pero el
--  diagnostico era mas grande: no era el bot, era CUALQUIERA.
--
--  Lo que estaba pasando, comprobado con la llave anon y SIN sesion de nadie
--  (esa llave viaja dentro del bundle de omm-erp.vercel.app):
--    · payroll_periods  28 periodos, con los totales de la semana
--    · facturas         4,064
--    · bank_movements   3,808
--    · employees        53, con sueldo, RFC, CURP e IMSS
--    · candidatos       33
--    · design_rules     28 (las reglas del cotizador)
--    · y se podia INSERTAR y BORRAR un lead
--
--  Causa: 117 de 138 tablas tenian una politica `using (true)` para el rol
--  publico. RLS prendida en 137 de 138 — el tablero de Supabase en verde — pero
--  una politica que dice `true` no restringe nada. La unica tabla con politicas
--  reales era app_users, de la migracion de Auth.
--
--  Habia una SEGUNDA familia que el primer barrido no atrapo porque no dice
--  literalmente `true`: politicas con `auth.role() = 'anon'` como puerta
--  trasera. Dejaban a un anonimo leyendo y escribiendo obras, planes semanales,
--  asignacion diaria de instaladores, caja chica, ausencias, asistencia y
--  live_locations (la ubicacion GPS de la gente).
--
--  Y dos vistas, v_cobranza_lead y v_cobranza_cotizacion, corrian con los
--  derechos de su dueño (sin security_invoker), asi que se saltaban el RLS de
--  las tablas de abajo: cualquier usuario con sesion leia por ahi la posicion
--  completa de cobranza.
--
--  ── El modelo que quedo ──────────────────────────────────────────────────
--
--    CONFIG  — definen COMO funciona el ERP (design_rules, catalogo,
--              plantillas, sla_config). Las lee cualquiera con sesion, las
--              escribe solo DG. Misma regla que ya obedecen los bots.
--    ADMIN   — dinero y personas (facturas, nomina, conciliacion, bancos,
--              candidatos, la bitacora de los bots). Solo DG y Administracion.
--    SESION  — el resto de la operacion: cualquiera con sesion activa.
--    OBRA    — los instaladores de la app de campo, que entran con Supabase
--              Auth pero NO tienen fila en app_users: alcanzan exactamente las
--              27 tablas que consulta src/obra-app, y nada de dinero.
--    ANONIMO — solo lo que necesita el examen publico de reclutamiento, que es
--              el unico flujo sin login. candidatos, ademas, acotado a los que
--              tienen un examen asignado.
--    BOTS    — cero por la pantalla. Un bot opera por su MCP, que si esta
--              acotado por tabla y por columna (ver acotar.ts).
--
--  ── Como se derivo, y como se verifico ──────────────────────────────────
--
--  Los niveles NO salieron de mi criterio: se mapeo cada tabla a las paginas
--  que la consultan (siguiendo el grafo de imports desde App.tsx) y cada pagina
--  a las areas que pueden abrirla. Las 11 tablas que hoy solo tocan paginas de
--  DG/Administracion son las que quedaron en ADMIN.
--
--  La verificacion se hizo con los privilegios REALES de cada usuario, no con
--  la llave de servicio:
--      begin;
--        select set_config('request.jwt.claims',
--          json_build_object('sub', '<auth_user_id>', 'role','authenticated')::text, true);
--        set local role authenticated;
--        ... contar filas, intentar escrituras ...
--      rollback;
--  Es la misma leccion que la validacion de Cobranza aprendio a golpes: medir
--  con los permisos del consumidor, no con los del que revisa.
--
--  Resultado final: las 9 personas ven 19 de 20 tablas operativas (la 20a,
--  change_orders, esta vacia), DG y Administracion ven 9 de 9 de dinero, las
--  otras cinco areas 0 de 9, los 10 instaladores activos 12 de 20 y 0 de dinero,
--  los 2 bots 0 de 20, y un anonimo 0 en todo salvo el examen.
--
--  ── Dos tropiezos mios, anotados porque el patron se repite ─────────────
--
--  1. El paso que repone el nivel solo miraba tablas con CERO politicas. Las
--     tablas de obra ya tenian la del instalador, asi que se las salto y la
--     oficina quedo sin poder escribir obras ni planes semanales. De ahi salio
--     la vista v_rls_sin_oficina, que lista cualquier tabla con RLS que ninguna
--     politica abra a un usuario de oficina.
--  2. Sonde escrituras con `update ... where id = '<uuid inexistente>'`. Eso
--     SIEMPRE "funciona": RLS filtra RENGLONES, y filtrar a cero no es un error.
--     Para medir permiso de escritura hay que INSERTAR (el WITH CHECK se evalua
--     contra la fila nueva) o actualizar una fila que exista. Tres veces me dio
--     un falso negativo por usar ademas una columna que no existia en la tabla.
--
--  ── Lo que quedo ABIERTO a proposito, y por que ─────────────────────────
--
--  · employees carga salary_base, salary_fiscal, rfc, curp e imss_numero en la
--    misma fila que el nombre y el puesto. RLS es por RENGLON, no por columna,
--    y el padron lo necesitan todas las pantallas para poner nombres. Asi que
--    hoy cualquiera con sesion puede leer sueldos por la API. Se arregla
--    moviendo esas columnas a su propia tabla: toca /nomina, /empleados y
--    /finanzas, y va aparte.
--  · bank_movements, cash_movements y payment_allocations quedaron en SESION y
--    no en ADMIN porque /crm/:id las lee para el estado de cuenta del lead.
--    Acotarlas bien es por RENGLON (solo los movimientos de ESE lead), no por
--    area, y eso es una decision de producto: ¿Ventas debe ver el estado de
--    cuenta de su cliente? Probablemente si — pero que lo diga Elias.
-- ═══════════════════════════════════════════════════════════════════════════

-- Ver las migraciones aplicadas para el cuerpo completo:
--   rls_ayudantes_de_politica              hay_sesion, mi_area, soy_bot, es_area, usuario_real
--   rls_permisos_por_area                  el barrido de las 117 + los tres niveles
--   rls_examen_publico_anonimo             las 5 tablas del examen, y candidatos acotado
--   rls_vistas_cobranza_security_invoker   las vistas dejan de saltarse el RLS
--   rls_employees_padron_legible           el padron se lee parejo, se escribe desde Admin
--   rls_instaladores_app_de_obra           soy_instalador() + sus 27 tablas
--   rls_segunda_familia_puertas_de_anon    las politicas con auth.role() = 'anon'
--   rls_reponer_nivel_en_tablas_de_obra    el tropiezo 1 + la vista v_rls_sin_oficina
--   rls_retier_catalogo_operativo          el error de clasificacion del catalogo


-- ═══════════════════════════════════════════════════════════════════════════
--  2026-09-28 — El catalogo NO era configuracion. Correccion de un error mio.
--
--  Nimbe reporto: "Error al crear producto: new row violates row-level
--  security policy for table catalog_products". Causa: yo puse esa tabla en el
--  nivel CONFIG (escritura solo DG) razonando que es "el precio maestro".
--
--  ── Como se decide si una tabla es configuracion ────────────────────────
--
--  No por lo que la tabla SIGNIFICA — por eso me equivoque. "Precio maestro"
--  suena a configuracion. Se decide por dos cosas medibles:
--
--    a) la frecuencia con que se escribe
--    b) si su pantalla en el ERP tiene allowedAreas
--
--  catalog_products: 2,377 filas, 1,194 creadas en 90 dias, 243 en septiembre.
--  /catalogo sin allowedAreas, y en la lista blanca de Mantenimiento a
--  proposito. Las dos señales dicen operativo. Configuracion de verdad se ve
--  distinto: design_rules, sla_config, project_phase_templates,
--  prerequisitos_catalogo, entregable_tipos, plantilla_actividades,
--  plantillas_encargo y supplier_quote_playbooks llevan CERO escrituras en 90
--  dias, y /reglas-ai ya estaba en allowedAreas={['DG']}. Esas se quedan.
--
--  ── Lo que rompia ademas del catalogo, sin que nadie lo reportara ───────
--
--  Arreglar solo lo que se quejo habria dejado cuatro trampas puestas. Se
--  buscaron rastreando quien ESCRIBE cada tabla en el codigo, no adivinando:
--
--    catalog_bundles / catalog_bundle_items  bundlesIlum.ts — "Guardar como
--                                            bundle" en el cotizador de Ilum
--    suppliers                               Compras.tsx, alta de distribuidor
--    maintenance_settings                    MaintQuotes.savePrecio(), Axel
--    project_task_templates                  TemplatesManager en /proyectos
--
--  Las cuatro primeras quedaron en escritura por cualquier usuario real (el
--  nivel que su pantalla siempre tuvo). maintenance_settings paso a
--  Mantenimiento, project_task_templates a Ventas_Ingenieria, y vacantes +
--  capacitaciones/bloques/preguntas a Administracion, que es donde vive
--  Reclutamiento. DELETE se queda en DG en las cuatro operativas: ninguna
--  pantalla borra en duro (Catalogo apaga con is_active = false), asi que
--  nadie pierde una funcion.
--
--  ── Lo que NO cambio, y es el punto ────────────────────────────────────
--
--  CONFIGURACION_DEL_ERP en acotar.ts sigue prohibiendo que CUALQUIER MCP
--  escriba catalog_products, suppliers, design_rules y las demas. La regla de
--  Elias — un bot opera el ERP, nunca cambia como funciona — se sostiene del
--  lado del bot, que es donde tiene que sostenerse. RLS protege de las
--  personas equivocadas; acotar.ts protege de los bots. Confundir las dos
--  capas fue el error: le puse a las personas un candado que era para el bot.
--
--  ── Tercer tropiezo mio, y es el peor de los tres ───────────────────────
--
--  El script que verifico esto INSERTA de verdad (es la unica sonda valida —
--  ver el tropiezo 2 arriba), y lo corri en un bloque DO sin transaccion. El
--  MCP le hizo commit: quedaron 32 filas '_PRUEBA_RLS_' en catalog_products,
--  catalog_bundles, suppliers, vacantes y capacitaciones. Se borraron y se
--  confirmo cero, y que maintenance_settings conservara su unica fila real.
--
--  Regla: una sonda de escritura va SIEMPRE dentro de begin; ... rollback;.
--  "Se revierte solo" no es cierto en un DO block — el bloque es una sola
--  transaccion que el cliente confirma al terminar. set_config(...,true) es
--  local a la transaccion, no la revierte.
--
--  ── Verificacion ───────────────────────────────────────────────────────
--
--  INSERT real simulando las 11 cuentas con auth_user_id, tabla por tabla:
--  las 9 personas escriben catalog_products, catalog_bundles y suppliers; los
--  2 bots 0 de 8. maintenance_settings solo Mantenimiento y DG;
--  project_task_templates solo Ventas_Ingenieria y DG; vacantes y
--  capacitaciones solo Administracion y DG; design_rules solo DG.
--
--  ── Hallazgo aparte, para Elias, no se puede arreglar desde aqui ───────
--
--  Nimbe no estaba usando su cuenta: nimbe@omniious.com no tiene fila en
--  auth.users, asi que no puede iniciar sesion. Las CINCO cuentas de
--  Operaciones estan asi (Nimbe, Adrian, Ernesto, Paulina, Felipe): entran
--  con la cuenta de alguien mas. Mientras eso siga, los permisos por area no
--  significan nada — cinco personas de Operaciones pueden estar entrando como
--  Logistica — y el ERP no puede decir quien cambio un precio. Cada uno tiene
--  que poner su propia contraseña en /login; el flujo ya existe.
--
--  ── El hueco que queda y es decision de producto ───────────────────────
--
--  Capacitaciones.tsx enseña el boton "Editar" a todos, no solo a DG. El RLS
--  ahora lo limita a Administracion, asi que a los demas el boton los va a
--  mandar a un error en vez de esconderse. Quien arma un examen no deberia ser
--  quien lo contesta, pero el arreglo correcto es ocultar el boton — y eso es
--  UI, no permisos.
-- ═══════════════════════════════════════════════════════════════════════════
