-- ═══════════════════════════════════════════════════════════════════════════
--  FOLIOS OMM — aplicado en produccion el 2026-09-25
--
--   Lead        PILO                4 letras del nombre, unicas
--   Cotizacion  PILO-ES01           nucleo fijo; COT- solo es etiqueta
--   Compra      PILO-ES01-C03       tercera compra de ese contrato
--
--  El folio se genera en la base y no en la pantalla: asi nace igual si el
--  registro lo crea el ERP, una importacion o un script.
--
--  Autoasignacion bancaria: al llegar un movimiento, el concepto se compara en
--  forma compacta (solo letras y numeros) contra los folios. Si aparece el de
--  una compra se asigna lead + cotizacion + orden; si solo aparece el del
--  contrato, lead + cotizacion. La clave de lead sola NO asigna: cuatro letras
--  pegan por casualidad dentro de cualquier palabra.
--
--  Este archivo es la copia de lo aplicado (Supabase migrations
--  folios_omm_columnas_y_funciones, folios_omm_triggers,
--  folios_omm_fix_enum_specialty y folios_omm_autoasignacion_bancaria).
--  Se guarda en el repo para que el esquema no viva solo en el dashboard.
-- ═══════════════════════════════════════════════════════════════════════════

-- Columnas
alter table leads            add column if not exists codigo text;
alter table quotations       add column if not exists folio  text;
alter table purchase_orders  add column if not exists folio  text;
alter table bank_movements   add column if not exists folio_detectado text;
alter table bank_movements   add column if not exists asignacion_auto boolean default false;

create unique index if not exists uq_leads_codigo      on leads (codigo)           where codigo is not null;
create unique index if not exists uq_quotations_folio  on quotations (folio)       where folio  is not null;
create unique index if not exists uq_po_folio          on purchase_orders (folio)  where folio  is not null;

-- Las funciones y disparadores completos estan en las migraciones de Supabase:
--   omm_normaliza, omm_compacta
--   omm_lead_codigo_base, omm_lead_codigo_unico, omm_tg_lead_codigo
--   omm_specialty2, omm_lead_de_cotizacion
--   omm_folio_cotizacion, omm_tg_cot_folio
--   omm_folio_compra,     omm_tg_po_folio
--   omm_folio_en_concepto, omm_tg_movimiento_folio

-- Edicion de la clave (migracion folios_omm_editar_clave_lead):
--   omm_sugerir_codigo(nombre)                 propuesta para la pantalla de alta
--   omm_codigo_disponible(codigo, lead)        validacion en vivo
--   omm_cambiar_codigo_lead(lead, nuevo, forzar)
--     Cambia la clave y arrastra los folios de cotizaciones y compras. Si algun
--     folio ya aparece en un movimiento bancario, exige confirmacion: ese numero
--     ya vive fuera del sistema (en el banco, en un correo, en un expediente).

-- 2026-09-25 (folios_omm_clave_hasta_8): la clave admite hasta 8 caracteres.
-- El limite de 6 era invento: las claves reales del equipo son L202T, RDA101,
-- F2BA101. Con 8, F2BA101-ES01-C03 son 16 caracteres de los 40 del concepto.

-- 2026-09-25 (folios_omm_compras_sin_cotizacion): el folio es EL identificador
-- de una orden de compra. Las compras de bodega, que no cuelgan de ninguna
-- cotizacion, toman su propio consecutivo OC-AAMM-nnn como folio: es el numero
-- con el que ya salieron a los proveedores. El consecutivo se queda en la base
-- para todas, pero ya no se muestra ni se imprime.

-- 2026-09-25 (folios_omm_proyecto_por_ingenieria_v2): las cotizaciones de
-- proyecto llevan la ingenieria en el folio — PR-IE electrica, PR-IESP
-- especiales, PR-ILU iluminacion. El tipo sale de notes.tipoProyecto y, si
-- falta, se infiere del nombre igual que lo hace Finanzas. Si el proyecto
-- cambia de ingenieria el folio se rehace solo, salvo que ya tenga compras o
-- transferencias colgando: un folio emitido manda sobre la prolijidad.

-- ═══════════════════════════════════════════════════════════════════════════
--  Versiones: la copia HEREDA el núcleo del folio (2026-09-29)
--  Migraciones: `folios_omm_version_hereda_el_nucleo`,
--               `folios_omm_folio_repetido_se_reasigna`
--
--  Elias: "Error clonando cotización: duplicate key value violates unique
--  constraint uq_quotations_folio".
--
--  `VersionManager` copiaba la fila entera para hacer una versión —folio
--  incluido— y el índice único la rechazaba. **El botón «Nueva versión» estaba
--  muerto desde que existen los folios OMM (2026-09-26)**: antes la columna no
--  existía, así que el defecto nació con esta misma familia de migraciones y
--  nadie lo notó hasta hoy.
--
--  ── La regla (decisión de Elias) ────────────────────────────────────────
--
--      DLAN-ES01     original
--      DLAN-ES01-B   versión B          ← NO DLAN-ES02
--      DLAN-ES01-OP2 versión "OP 2"
--
--  Una versión es la MISMA oferta con otra opción (con o sin instalación,
--  Lutron o Control4), no una cotización más del cliente. Con consecutivo
--  propio el número deja de decir cuántas cotizaciones distintas tiene el
--  lead: hoy Landmark parece tener tres de iluminación (IL01, IL02, IL03)
--  cuando son dos, una con dos opciones.
--
--  Es la misma regla que ya gobierna el prefijo COT-: **el núcleo nunca
--  cambia, lo que cambia se pega a los lados.**
--
--  ── Cómo queda ──────────────────────────────────────────────────────────
--
--  `omm_cola_de_version(label)` (NUEVA) — la etiqueta lista para un folio:
--  mayúsculas, solo letras y números, 4 caracteres a lo más. Las etiquetas que
--  escribe la gente son sucias ("V 2", "2.0", "ML Slim") y un folio tiene que
--  poder dictarse por teléfono. Si no queda nada utilizable devuelve NULL y se
--  cae al consecutivo.
--
--  `omm_tg_cot_folio` ahora:
--   1. Si la fila trae `version_group_id` y etiqueta, busca la RAÍZ —la
--      hermana más vieja cuyo folio NO trae cola— y le pega la etiqueta. Por
--      eso la versión de una versión cuelga del original: B→C da ES01-C, no
--      ES01-B-C.
--   2. Acepta como válido `^clave-SUF[0-9]+(-[A-Z0-9]{1,4})?$`, o si no
--      reescribiría el folio de versión que acaba de poner.
--   3. **Un folio ya ocupado SIEMPRE se reasigna**, aunque las protecciones de
--      compras y movimientos digan que no se toque: ahí la disyuntiva es folio
--      nuevo o nada, y "nada" significa que el usuario no puede guardar. Esto
--      hace que CUALQUIER camino que clone una cotización quede bien —hay
--      cinco que insertan en `quotations`, y mañana un bot— y no solo el botón.
--   4. Dos versiones con la misma etiqueta caen al consecutivo. No se fuerza.
--
--  ── Lo que NO se tocó ───────────────────────────────────────────────────
--
--  Los 65 folios de versiones ya emitidos se quedan con su consecutivo. Seis
--  tienen órdenes de compra colgando. Un folio que ya circuló no se renumera:
--  esa es la razón de ser de la protección del punto 3, no una excepción a
--  ella.
--
--  ── Verificación (sesión de Alfredo Rosas, dentro de begin/rollback) ─────
--
--  | prueba                                      | resultado          |
--  |---------------------------------------------|--------------------|
--  | clon tal como lo hace el botón HOY (con folio) | DLAN-ES01-B     |
--  | etiqueta sucia "OP 2"                       | DLAN-ES01-OP2      |
--  | versión de la versión (B → C)               | DLAN-ES01-C        |
--  | etiqueta repetida (B otra vez)              | DLAN-ES02          |
--  | cotización NUEVA de verdad                  | siguiente consecutivo |
--  | editar la versión                           | folio intacto      |
--
--  Detección bancaria, con las tres formas que manda el banco:
--   "REF DLAN-ES01-B" → versión B · "REF DLAN-ES01" → la A ·
--   "DLANES01B" (sin guiones) → versión B.
--  Funciona porque `omm_folio_en_concepto` ordena por `length(folio) desc`: la
--  cola se lee sola, no hubo que tocar esa función.
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
--  La OC toma su folio al LIGARLE la cotización, no solo al nacer (2026-09-30)
--  Migración: `folios_omm_oc_asciende_al_ligar_cotizacion`
--
--  Elias: "en algunas cotizaciones está siguiendo bien el foliado y en otras
--  no, aunque sí estén adjudicadas a un proyecto".
--
--  ── La causa: CUÁNDO se liga la cotización ──────────────────────────────
--
--    · OC que nace con cotización        → MAT-IE01-C22        ✔ (156 de 170)
--    · OC que nace sin ella y se liga
--      después (la OC manual la trae
--      OPCIONAL)                         → OC-2609-096, pegado ✘ (3)
--
--  El trigger escribía el consecutivo en `folio` como respaldo, y su primera
--  línea decía "si ya tiene folio, no lo toques". Ligarle la cotización
--  después no servía de nada.
--
--  Las tres se crearon sin cotización y se ligaron 115 segundos, 164 segundos
--  y 5 días más tarde. Las 156 buenas nacieron con la suya.
--
--  ── Lo que NO es defecto ────────────────────────────────────────────────
--
--  11 órdenes traen OC-26xx-nnn y está bien: no cuelgan de cotización
--  (herramienta, insumos de rack, compras de bodega, canceladas). Ahí el
--  consecutivo ES el folio. El respaldo se conserva a propósito porque
--  `omm_folio_en_concepto` lo usa para amarrar transferencias.
--
--  ── La regla nueva ──────────────────────────────────────────────────────
--
--  Una orden con folio de respaldo que recibe cotización se ASCIENDE, pero
--  solo mientras nada dependa del número viejo: en borrador o aprobada, sin
--  pagos y sin transferencia que ya lo traiga. Una 'pedida' ya salió con ese
--  número impreso en el PDF del proveedor.
--
--  ⚠️ EL TRIGGER ES `BEFORE INSERT OR UPDATE **OF quotation_id**`.
--
--  Solo corre cuando `quotation_id` va en el SET. La primera prueba tocaba
--  `updated_at` y no pasaba nada — parecía que el arreglo no servía, y lo que
--  no servía era la prueba. Para reparar una fila a mano:
--
--      update purchase_orders set quotation_id = quotation_id where ...
--
--  ── Verificación (transacción revertida, 5 casos) ───────────────────────
--
--  | caso                                | resultado            |
--  |-------------------------------------|----------------------|
--  | borrador + cotización con folio     | R222-IE01-C03    ✔   |
--  | borrador + cotización con folio     | OFP1-IE01-C09    ✔   |
--  | **pedida** + cotización con folio   | no se toca       ✔   |
--  | ya tenía folio OMM                  | no se toca       ✔   |
--  | sin cotización                      | consecutivo      ✔   |
--
--  Aplicado a las dos en borrador. Quedan 158 correctas, 11 con consecutivo
--  legítimo y 1 (OC-2609-092, ya pedida) esperando que Elias diga si se
--  renumera o se deja.
-- ═══════════════════════════════════════════════════════════════════════════
